[package]
authors = ["Cayden <longwelldotpy@gmail.com>"]
categories = ["api-bindings"]
description = "A low level api wrapper for Rolimons.com."
edition = "2021"
keywords = ["roblox", "api", "roblox api"]
license = "MIT"
name = "roboat"
readme = "README.md"
repository = "https://github.com/Chloe-Woahie/roli-rs"
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
