[package]
authors = ["Cayden <longwelldotpy@gmail.com>"]
categories = ["api-bindings"]
description = "A high performance interface for the Roblox API."
edition = "2021"
keywords = ["roblox", "api", "roblox-api"]
license = "MIT"
name = "roboat"
readme = "README.md"
repository = "https://github.com/Chloe-Woahie/roboat"
version = "0.10.1"

[dependencies]
reqwest = { version = "0.11.14", default-features=false, features = ["rustls-tls", "json"] }
thiserror = "1.0.40"
serde = {version="1.0.136", features=["derive"]}
serde_json = "1.0.94"
tokio = { version = "1.27.0", features = ["full"] }

[dev-dependencies]
clap = { version = "4.1.13", features = ["derive"] }