[package]
authors = ["Cayden <longwelldotpy@gmail.com>"]
categories = ["api-bindings"]
description = "An api wrapper for Roblox.com."
edition = "2021"
keywords = ["roblox", "api", "roblox-api"]
license = "MIT"
name = "roboat"
readme = "README.md"
repository = "https://github.com/Chloe-Woahie/roboat"
version = "0.0.0-placeholder"

[dependencies]
reqwest = { version = "0.11.14", default-features=false, features = ["rustls-tls"] }
